### ISSUE TITLE
beta branch error

### ISSUE THREAD

**Issue by iamnotstone** [donalffons/opencascade.js-examples#19]
hello ! when I am trying to run this example in beta branch, it shows a error:
"mainJS is not a constructor"

What is the "mainJS" supposed to be in beta version ?

**Comment by donalffons** [comment]
Hi, I think this was an issue with the lockfile (i.e. `yarn.lock`). Probably yarn didn't pick up the updated opencascade.js version, because `yarn.lock` still contained a reference to an older beta version.

Probably the issue is that the beta versions are not using semantic versioning.

Could you `git pull` the beta branch again and check if it works now for you?

**Comment by donalffons** [comment]
...I just noticed that this probably still might cause issues. Changing the version number from `"opencascade.js": "^2.0.0-beta.bf4d306"` to `"opencascade.js": "2.0.0-beta.bf4d306"` is hopefully going to fix this for real this time.

**Comment by iamnotstone** [comment]
thanks! this time it works.
